name: Test Conda Installation Script

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install wget curl

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install curl -y

    - name: Make shell script executable
      if: matrix.os != 'windows-latest'
      run: chmod +x ./install_conda.sh

    - name: Run shell script on Linux and macOS
      if: matrix.os != 'windows-latest'
      shell: sh
      run: ./install_conda.sh

    - name: Run batch script on Windows
      if: matrix.os == 'windows-latest'
      run: |
        ./install_conda.bat

    - name: Check conda installation on Linux and macOS
      if: matrix.os != 'windows-latest'
      run: |
        source ~/.profile
        conda --version

    - name: Check conda installation on Windows
      if: matrix.os == 'windows-latest'
      run: |
        $env:Path += ';C:\Users\runneradmin\miniconda3\Scripts'
        conda --version
