name: Test Zsh Script

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies on Linux and macOS
      if: matrix.os != 'windows-latest'
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y zsh wget curl
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install zsh wget curl
        fi

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install zsh curl -y
        choco install wget -y

    - name: Make script executable
      if: matrix.os != 'windows-latest'
      run: chmod +x ./install_conda.zsh

    - name: Run zsh script on Linux and macOS
      if: matrix.os != 'windows-latest'
      shell: zsh
      run: ./install_conda.zsh

    - name: Run zsh script on Windows
      if: matrix.os == 'windows-latest'
      run: |
        zsh ./install_conda.zsh

    - name: Check conda installation on Linux and macOS
      if: matrix.os != 'windows-latest'
      run: |
        source ~/.zshrc
        conda --version

    - name: Check conda installation on Windows
      if: matrix.os == 'windows-latest'
      run: |
        $env:Path += ';C:\Users\runneradmin\miniconda3\Scripts'
        conda --version
